DIR_NAME_SEP = '_'

IRECO_TAG_SEP = '#'
IRECO_WORD_SEP = '.'

MIN_IRECO_PARTS = 1
MAX_IRECO_PARTS = 6

IRECO_PART_MIN_LEN = 1
IRECO_PART_MAX_LEN = 16

ALPHA_CODE_MIN_LEN = 4
ALPHA_CODE_MAX_LEN = 5
ALPHA_CODE_SEP = ','

SPECIAL_PREFIX = 'SPECIAL'
