# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres_airtable_cache_db:
    image: postgres:15.3
    container_name: postgres_airtable_cache_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airtable_cache